//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: treadstone.proto
namespace UNO
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginInfo")]
  public partial class LoginInfo : global::ProtoBuf.IExtensible
  {
    public LoginInfo() {}
    
    private string _user;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"user", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string user
    {
      get { return _user; }
      set { _user = value; }
    }
    private int _room_number;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"room_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int room_number
    {
      get { return _room_number; }
      set { _room_number = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomInfo")]
  public partial class RoomInfo : global::ProtoBuf.IExtensible
  {
    public RoomInfo() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _number;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int number
    {
      get { return _number; }
      set { _number = value; }
    }
    private bool _locked;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"locked", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool locked
    {
      get { return _locked; }
      set { _locked = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomDetail")]
  public partial class RoomDetail : global::ProtoBuf.IExtensible
  {
    public RoomDetail() {}
    
    private int _number;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int number
    {
      get { return _number; }
      set { _number = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private int _timeout = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"timeout", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int timeout
    {
      get { return _timeout; }
      set { _timeout = value; }
    }
    private UNO.RoomDetail.RoomState _state = UNO.RoomDetail.RoomState.Wait;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(UNO.RoomDetail.RoomState.Wait)]
    public UNO.RoomDetail.RoomState state
    {
      get { return _state; }
      set { _state = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"RoomState")]
    public enum RoomState
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Wait", Value=41)]
      Wait = 41,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Running", Value=42)]
      Running = 42
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserInfo")]
  public partial class UserInfo : global::ProtoBuf.IExtensible
  {
    public UserInfo() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private UNO.UserInfo.State _state;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public UNO.UserInfo.State state
    {
      get { return _state; }
      set { _state = value; }
    }
    private int _card_count;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"card_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int card_count
    {
      get { return _card_count; }
      set { _card_count = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"State")]
    public enum State
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"uno", Value=61)]
      uno = 61,
            
      [global::ProtoBuf.ProtoEnum(Name=@"idle", Value=62)]
      idle = 62,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ready", Value=63)]
      ready = 63
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayState")]
  public partial class PlayState : global::ProtoBuf.IExtensible
  {
    public PlayState() {}
    
    private int _now_card;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"now_card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int now_card
    {
      get { return _now_card; }
      set { _now_card = value; }
    }
    private bool _double_card;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"double_card", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool double_card
    {
      get { return _double_card; }
      set { _double_card = value; }
    }
    private bool _intercepted;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"intercepted", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool intercepted
    {
      get { return _intercepted; }
      set { _intercepted = value; }
    }
    private int _now_turn;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"now_turn", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int now_turn
    {
      get { return _now_turn; }
      set { _now_turn = value; }
    }
    private int _next_turn;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"next_turn", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int next_turn
    {
      get { return _next_turn; }
      set { _next_turn = value; }
    }
    private int _left_card;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"left_card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int left_card
    {
      get { return _left_card; }
      set { _left_card = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StatusInfo")]
  public partial class StatusInfo : global::ProtoBuf.IExtensible
  {
    public StatusInfo() {}
    
    private UNO.StatusInfo.StatusType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public UNO.StatusInfo.StatusType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private readonly global::System.Collections.Generic.List<UNO.UserInfo> _user_info = new global::System.Collections.Generic.List<UNO.UserInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"user_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<UNO.UserInfo> user_info
    {
      get { return _user_info; }
    }
  
    private UNO.RoomDetail _room_detail = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"room_detail", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public UNO.RoomDetail room_detail
    {
      get { return _room_detail; }
      set { _room_detail = value; }
    }
    private UNO.PlayState _play_state = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"play_state", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public UNO.PlayState play_state
    {
      get { return _play_state; }
      set { _play_state = value; }
    }
    private bool _all_user_updated = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"all_user_updated", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool all_user_updated
    {
      get { return _all_user_updated; }
      set { _all_user_updated = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"StatusType")]
    public enum StatusType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"User", Value=51)]
      User = 51,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Room", Value=52)]
      Room = 52,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Play", Value=53)]
      Play = 53
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginResult")]
  public partial class LoginResult : global::ProtoBuf.IExtensible
  {
    public LoginResult() {}
    
    private int _myID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"myID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int myID
    {
      get { return _myID; }
      set { _myID = value; }
    }
    private UNO.StatusInfo _status_info;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"status_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public UNO.StatusInfo status_info
    {
      get { return _status_info; }
      set { _status_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomMsg")]
  public partial class RoomMsg : global::ProtoBuf.IExtensible
  {
    public RoomMsg() {}
    
    private UNO.RoomMsg.Type _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public UNO.RoomMsg.Type type
    {
      get { return _type; }
      set { _type = value; }
    }
    private UNO.LoginInfo _login_info = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"login_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public UNO.LoginInfo login_info
    {
      get { return _login_info; }
      set { _login_info = value; }
    }
    private readonly global::System.Collections.Generic.List<UNO.RoomInfo> _room_info = new global::System.Collections.Generic.List<UNO.RoomInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"room_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<UNO.RoomInfo> room_info
    {
      get { return _room_info; }
    }
  
    private UNO.LoginResult _login_result = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"login_result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public UNO.LoginResult login_result
    {
      get { return _login_result; }
      set { _login_result = value; }
    }
    private UNO.RoomDetail _room_detail = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"room_detail", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public UNO.RoomDetail room_detail
    {
      get { return _room_detail; }
      set { _room_detail = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Type")]
    public enum Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetList", Value=0)]
      GetList = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ListResult", Value=1)]
      ListResult = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Login", Value=2)]
      Login = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LoginResult", Value=3)]
      LoginResult = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Create", Value=4)]
      Create = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Setting", Value=5)]
      Setting = 5
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CardInfo")]
  public partial class CardInfo : global::ProtoBuf.IExtensible
  {
    public CardInfo() {}
    
    private int _count;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _number = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> number
    {
      get { return _number; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DoubtInfo")]
  public partial class DoubtInfo : global::ProtoBuf.IExtensible
  {
    public DoubtInfo() {}
    
    private int _user_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameMsg")]
  public partial class GameMsg : global::ProtoBuf.IExtensible
  {
    public GameMsg() {}
    
    private UNO.GameMsg.Type _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public UNO.GameMsg.Type type
    {
      get { return _type; }
      set { _type = value; }
    }
    private UNO.GameMsg.ColorInfo _color_info = UNO.GameMsg.ColorInfo.Shit;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"color_info", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(UNO.GameMsg.ColorInfo.Shit)]
    public UNO.GameMsg.ColorInfo color_info
    {
      get { return _color_info; }
      set { _color_info = value; }
    }
    private UNO.CardInfo _card_info = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"card_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public UNO.CardInfo card_info
    {
      get { return _card_info; }
      set { _card_info = value; }
    }
    private UNO.StatusInfo _status_info = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"status_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public UNO.StatusInfo status_info
    {
      get { return _status_info; }
      set { _status_info = value; }
    }
    private UNO.DoubtInfo _doubt_info = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"doubt_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public UNO.DoubtInfo doubt_info
    {
      get { return _doubt_info; }
      set { _doubt_info = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Type")]
    public enum Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayCard", Value=11)]
      PlayCard = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayCardResult", Value=12)]
      PlayCardResult = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DrawCard", Value=13)]
      DrawCard = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DrawCardResult", Value=14)]
      DrawCardResult = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNO", Value=15)]
      UNO = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Ready", Value=16)]
      Ready = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Doubt", Value=17)]
      Doubt = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Status", Value=18)]
      Status = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Done", Value=19)]
      Done = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Black", Value=20)]
      Black = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Timeout", Value=21)]
      Timeout = 21
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ColorInfo")]
    public enum ColorInfo
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Shit", Value=31)]
      Shit = 31,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Blue", Value=32)]
      Blue = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Green", Value=33)]
      Green = 33,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Yellow", Value=34)]
      Yellow = 34,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Red", Value=35)]
      Red = 35
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatMsg")]
  public partial class ChatMsg : global::ProtoBuf.IExtensible
  {
    public ChatMsg() {}
    
    private long _time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long time
    {
      get { return _time; }
      set { _time = value; }
    }
    private int _userID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"userID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userID
    {
      get { return _userID; }
      set { _userID = value; }
    }
    private string _content;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ScoreInfo")]
  public partial class ScoreInfo : global::ProtoBuf.IExtensible
  {
    public ScoreInfo() {}
    
    private int _userID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userID
    {
      get { return _userID; }
      set { _userID = value; }
    }
    private int _score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ScoreMsg")]
  public partial class ScoreMsg : global::ProtoBuf.IExtensible
  {
    public ScoreMsg() {}
    
    private readonly global::System.Collections.Generic.List<UNO.ScoreInfo> _score_info = new global::System.Collections.Generic.List<UNO.ScoreInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"score_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<UNO.ScoreInfo> score_info
    {
      get { return _score_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UNOMsg")]
  public partial class UNOMsg : global::ProtoBuf.IExtensible
  {
    public UNOMsg() {}
    
    private UNO.UNOMsg.Type _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public UNO.UNOMsg.Type type
    {
      get { return _type; }
      set { _type = value; }
    }
    private long _sequence;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sequence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long sequence
    {
      get { return _sequence; }
      set { _sequence = value; }
    }
    private UNO.RoomMsg _room_msg = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"room_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public UNO.RoomMsg room_msg
    {
      get { return _room_msg; }
      set { _room_msg = value; }
    }
    private UNO.GameMsg _game_msg = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"game_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public UNO.GameMsg game_msg
    {
      get { return _game_msg; }
      set { _game_msg = value; }
    }
    private UNO.ChatMsg _chat_msg = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"chat_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public UNO.ChatMsg chat_msg
    {
      get { return _chat_msg; }
      set { _chat_msg = value; }
    }
    private string _error_msg = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"error_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string error_msg
    {
      get { return _error_msg; }
      set { _error_msg = value; }
    }
    private UNO.ScoreMsg _score_msg = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"score_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public UNO.ScoreMsg score_msg
    {
      get { return _score_msg; }
      set { _score_msg = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Type")]
    public enum Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Room", Value=91)]
      Room = 91,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Game", Value=92)]
      Game = 92,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Chat", Value=93)]
      Chat = 93,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error", Value=94)]
      Error = 94,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Score", Value=95)]
      Score = 95
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}